spring:
  application:
    name: spring-s3-sqs-notifications
  cloud:
    aws:
      region:
        static: us-east-1
      sqs:
        endpoint: http://sqs.${spring.cloud.aws.region.static}.localhost.localstack.cloud:4566
      credentials:
        access-key: test
        secret-key: test
      s3:
        endpoint: http://s3.${spring.cloud.aws.region.static}.localhost.localstack.cloud:4566
        bucket: user-bucket

queue:
  todo:
    name: user-todo-s3-event-notification-queue
  profile:
    name: user-profile-s3-event-notification-queue

data-population:
  user:
    s3:
      enabled: false
